### PR TITLE
Abdullah

### PR DESCRIPTION
**Pull request by ShacMiester**

### CODE REVIEW

**Comment by alanorth** [comment]
@ShacMiester thank you. I deployed your branch on [AReS](https://cgspace.cgiar.org/explorer/) and I have some feedback:

- I still have duplicated icons. (#69) ✗
- The `.keyword` filter issue is fixed (#63) ✓
- Reset filters now clears the general search text, but now I notice that the year slider doesn't get reset... (#39) ✗
- The year slider bug is partially fixed. Now the slider doesn't change when you select an author, but notice that the number of available items is less than the number of openly accessible ones (#51) ✓/✗

I have cherry-picked the two working patches + the ngx-tour-core version bump above to master. We can closed this PR and you can work on the others. (Please make sure to rebase off ilri/master). I will leave all four of these patches deployed on AReS for now so you can see how they behave.

Thank you for the work!

**Comment by ShacMiester** [comment]
Will give them a good test, the duplicated icons are caused by the mechanism of adding data (now it adds configs in a correct form of data), there are key values inside the component configs needs to be changed (because of the old way of adding comps)

**Comment by ShacMiester** [comment]
I guess i figured out what's wrong with the slider, will implement that one line solution tomorrow @alanorth

**Comment by alanorth** [comment]
> duplicated icons are caused by the mechanism of adding data (now it adds configs in a correct form of data), there are key values inside the component configs needs to be changed (because of the old way of adding comps)

Does that mean we will need to delete and add the components again so that they are created with the new config?

**Comment by alanorth** [comment]
@ShacMiester I cherry-picked the fix for #69 to master. I tried to update the config in `backend/data/explorer.json` by removing one of the duplicate folder icons, for example, but it breaks the Explorer UI.

**Comment by ShacMiester** [comment]
> > duplicated icons are caused by the mechanism of adding data (now it adds configs in a correct form of data), there are key values inside the component configs needs to be changed (because of the old way of adding comps)
> 
> Does that mean we will need to delete and add the components again so that they are created with the new config?

No, we can directly edit the configurations of the components that are already stored!

**Comment by alanorth** [comment]
@ShacMiester see my previous comment. I deleted one of the duplicate folder icons and it broke the Explorer UI so I reverted the change. I don't think there is anything sensitive in there, so I will post it here for you to try to remove the duplicates:

[explorer.json.txt](https://github.com/ilri/OpenRXV/files/5938498/explorer.json.txt)

Uploaded as explorer.json.txt because GitHub doesn't allow attaching JSON files.

**Comment by ShacMiester** [comment]
Can you try this? @alanorth 
https://jsonblob.com/6cb6445f-694b-11eb-b382-df64311de814

**Comment by alanorth** [comment]
@ShacMiester Yes that worked for the folder icon. Can you do the same for the list icon? Thanks!

**Comment by alanorth** [comment]
@ShacMiester I've removed the last duplicate from the JSON. The trick was to not just remove the icon, but to add the `linkedWith` key. All good now! Thanks.

**Pull request closed without merging**
