### PR TITLE
Visual enhancements

### PR DESCRIPTION
**Pull request by mohammadsalem**
- Allow adding icons for counters.
- Counters redesign.
- Lists redesign.
- Allow specifying pie chart inner size.

### CODE REVIEW

**Comment by mohammadsalem** [comment]
**Counters:**
- From the admin design dashboard it is possible to select an icon that will appear in the card background.
- Counters are connected to each others and will always stretch to fill the row(s).
- Color change on hover will cover the whole counter area instead on only highlighting the content.
- Numeric filter is applied to add thousands commas.

**Lists:**
- The percentage is shown on the right without a share nor background.
- Numeric filter is applied to add thousands commas.

**Pie charts:**
- From the admin design dashboard it is possible to specify the inner size of the chart (will create a doughnut chart).

**Dashboard layout:**
- Margins between lines is removed.

**Admin design dashboard:**
- Each chart will show the chart title alongside the chart type (e.g. Top Countries - _list_)

**Comment by alanorth** [comment]
Thanks @mohammadsalem. Good to have a little bit of a visual refresh. Especially nice to have commas for the thousands!

Screenshot 2024-01-30 at 12-12-48 AReS

I'm wondering if the text in the counters could be left aligned or centered? And for the percentages in the lists, I don't know if anyone actually cares about those percentages, but it might be good to make them visually distinct like perhaps with a bootstrap pill or something so they stand out from the raw number.

Current AReS, for reference:

Screenshot 2024-01-30 at 12-18-12 AReS

Lastly, I hadn't noticed the grey gutter on the left until now. It stays there no matter the size of the window (both before and after). On the right side the graphics are flush with the icons.

**Comment by mohammadsalem** [comment]
@alanorth thanks for the feedback!
For the counters, the text is aligned top-left, numbers bottom-left and icon bottom right. I slightly increased the card hight for 10px to better fit 3 lines (two lines of text and one line of numbers).

I understood that these percentages are nice to have but not really important, so I wanted to give them less weight by removing the badge-like design. I increased the font a bit and changed the color to the theme color, do you think it is better now?

I changed the whole thing background color to white and reduced the padding on the left side (aligned with the logo in the header).

**Comment by alanorth** [comment]
Oh yeah that's looking better now. I hadn't noticed that the counter titles were aligned top left because I made my browser window smaller for the screenshot (it's 4K and I didn't want it to be huge).

Screenshot 2024-01-31 at 09-49-24 AReS

**Pull request merged**
