### PR TITLE
adding google maps component

### PR DESCRIPTION
**Pull request by ShacMiester**

### CODE REVIEW

**Comment by alanorth** [comment]
@ShacMiester Thanks. This is based on an old version of `master` so there are some issues:

- As of a month or so ago we run `npm run prettier` on all code to enforce code style and remove excessive whitespace
- As of several weeks ago we are now running Angular 9.1, so the `@agm` dependencies here are failing

I cherry-picked your changes and updated `@agm` to versions compatible with Angular 9.1 in my [ilri/OpenRXV/abdullah-google-maps](https://github.com/ilri/OpenRXV/tree/abdullah-google-maps) branch. Now I have an issue during `ng build`:

```console
ERROR in node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:41 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/google-maps-api-wrapper.d.ts:51:94 - error TS2314: Generic type 'MapHandlerMap<T>' requires 1 type argument(s).

51     subscribeToMapEvent<N extends keyof google.maps.MapHandlerMap>(eventName: N): Observable<google.maps.MapHandlerMap[N]>;
                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:93 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerMouseEventNames'.

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;
                                                                                               ~~~~~~~~~~~~~~~~~~~~~
node_modules/@agm/core/lib/services/managers/marker-manager.d.ts:26:129 - error TS2694: Namespace 'google.maps' has no exported member 'MarkerChangeOptionEventNames'.

26     createEventObservable<T extends (google.maps.MouseEvent | void)>(eventName: google.maps.MarkerMouseEventNames | google.maps.MarkerChangeOptionEventNames, marker: AgmMarker): Observable<T>;
```

I'm troubleshooting it, looking at issues on angular-google-maps (for example, https://github.com/SebastianM/angular-google-maps/issues/1893)

**Comment by alanorth** [comment]
I got this to build and run using an explicit dev dependency of `@types/googlemaps@3.39.12` in my [ilri/OpenRXV/abdullah-google-maps](https://github.com/ilri/OpenRXV/tree/abdullah-google-maps) branch. The issue is now that API key is not defined. Where are we supposed to define that?

Screenshot 2021-09-06 at 11-49-24 AReS-fs8

**Comment by moayadnajd** [comment]
> I got this to build and run using an explicit dev dependency of `@types/googlemaps@3.39.12` in my [ilri/OpenRXV/abdullah-google-maps](https://github.com/ilri/OpenRXV/tree/abdullah-google-maps) branch. The issue is now that API key is not defined. Where are we supposed to define that?
> 
> Screenshot 2021-09-06 at 11-49-24 AReS-fs8

this file contain the api key frontend/src/app/app.module.ts

but this should be changed to environment variable

**Comment by moayadnajd** [comment]
merged manually

**Pull request closed without merging**
