### PR TITLE
Auto import Meta data

### PR DESCRIPTION
**Pull request by ShacMiester**

### CODE REVIEW

**Comment by alanorth** [comment]
@ShacMiester is the commit for #48 using the `/rest/registries/schema` endpoint? I don't see it in the code. And this only works on DSpace 6 (CGSpace). How do we handle DSpace 5 (MELSpace, WorldFish)?

**Comment by ShacMiester** [comment]
> @ShacMiester is the commit for #48 using the `/rest/registries/schema` endpoint? I don't see it in the code. And this only works on DSpace 6 (CGSpace). How do we handle DSpace 5 (MELSpace, WorldFish)?

Well, that's temporary..untill we add a generic mechanism that handles any endpoint, the old end points you used are still handled as it should be, right?

**Comment by alanorth** [comment]
@ShacMiester so what does this commit do? It seems to just add some error handling? I think you could check the status endpoint to see which version the DSpace instance is running, and then act accordingly. For example:

- DSpace 5 on MELSpace: https://repo.mel.cgiar.org/rest/status
- DSpace 6 on CGSpace: https://dspacetest.cgiar.org/rest/status

If the API version is 6 you know that `/rest/registries/schema` will exist, otherwise you can do the DSpace 4/5 method of getting twenty-five items and extracting the metadata fields as a best guess.

**Comment by alanorth** [comment]
I just tested this and it works. Great job, @ShacMiester. The commits in this pull are a bit messy so I'll cherry-pick them into master manually.

**Pull request closed without merging**
