### PR TITLE
Enhancements Oct 2023

### PR DESCRIPTION
**Pull request by mohammadsalem**

### CODE REVIEW

**Comment by alanorth** [comment]
@mohammadsalem two minor things I noticed when trying to run this locally, added commits here:

https://github.com/ilri/OpenRXV/commits/enhancements-Oct-2023-alan

**Comment by mohammadsalem** [comment]
@alanorth thanks for the feedback!
> * Only 725 pages in Altmetric plugin? If that is 725*100 then there must be some missing?

In the DEV AReS not all handles are added in the plugins, but here is a comparison between the public API and the explorer API:
**Public API number of records for each prefix:**
- [10947](https://api.altmetric.com/v1/citations/at?num_results=1&handle_prefix=10947&page=1): 14
- [10568](https://api.altmetric.com/v1/citations/at?num_results=1&handle_prefix=10568&page=1): 13950
- [20.500.11766](https://api.altmetric.com/v1/citations/at?num_results=1&handle_prefix=20.500.11766&page=1): 4058
- [20.500.12348](https://api.altmetric.com/v1/citations/at?num_results=1&handle_prefix=20.500.12348&page=1): 1438

**Explorer API number of records for each prefix:**
- [10947](https://www.altmetric.com/explorer/api/research_outputs?key=b684fdb88941494598b392be23213fa0&digest=5993c7834c76119dcd38275e3d813a4cf0d16a39&filter%5Bhandle_prefix%5D=10947&filter%5Bscope%5D=all&page%5Bsize%5D=1&page%5Bnumber%5D=1): 524
- [10568](https://www.altmetric.com/explorer/api/research_outputs?key=b684fdb88941494598b392be23213fa0&digest=0c646daf8f8529699de33412fbfaefa7c400546d&filter%5Bhandle_prefix%5D=10568&filter%5Bscope%5D=all&page%5Bsize%5D=1&page%5Bnumber%5D=1): 68363
- [20.500.11766](https://www.altmetric.com/explorer/api/research_outputs?key=b684fdb88941494598b392be23213fa0&digest=c0a7194622d035f40768d004b2424f61cc9d2cb3&filter%5Bhandle_prefix%5D=20.500.11766&filter%5Bscope%5D=all&page%5Bsize%5D=1&page%5Bnumber%5D=1): 4065
- [20.500.12348](https://www.altmetric.com/explorer/api/research_outputs?key=b684fdb88941494598b392be23213fa0&digest=0b6fb42945879af0eab6e443ea22fcffde338989&filter%5Bhandle_prefix%5D=20.500.12348&filter%5Bscope%5D=all&page%5Bsize%5D=1&page%5Bnumber%5D=1): 1443

Note: The prefix **10947** is added to the plugins in the DEV server now.

> * On the _Repository Setup_ page the save button is on the bottom, but on most others it is on the top

The button is moved to the top to go with the other pages.

> * On the _Repository Setup_ page I think the show/hide arrows on the repository setup page are opposite? `^` should be hiding the content

Here I followed the same approach as for the explorer dashboard.
The arrows here represent the action to be done not the state, but we can change it in both places to represent the state if you think the current approach might be confusing. 
Screenshot 2023-10-25 at 4 23 33 PM
Screenshot 2023-10-25 at 4 23 23 PM


> * Collection filter has a weird blank space when scrolling down, I don't see this in other filters

This is strange and it is appearing in other dropdowns as well, it looks like an issue with the dropdown plugin, as it appears in the dropdowns having many options with long text. It is also happening here https://cgspace.cgiar.org/explorer/. Will investigate more.

> * Would it be possible to make the header for each section sticky so it stays at the top as you scroll? Not a huge thing, but some of the pages are really long

Nice suggestion, it is applied!

> * On the dashboard, I have a community filter using `parentcommunitylist`, but I don't see anything in the drop down

`parentcommunitylist` was not included in the CGSpace schema, I've added it `parentCommunity`: `parentcommunitylist`.

> * What is the syntax for the new advanced search? I tried `accessRights:"Open Access"` using the Elasticsearch field name and I _think_ it is working... we don't need any documentation or anything, but if I know then I can help people use it

The syntax is anything mentioned here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html and it is using all default values except for two parameters:
- `default_operator` it is set to **AND**.
- `fuzziness` is set to **auto**

**Comment by alanorth** [comment]
Thanks for the quick response. I see the changes are already live on the dev server. The sticky headers look great! And about the show/hide "^" I will look around the web and see how it is done elsewhere—something in my muscle memory feels backwards on that action.

Regarding Altmetric, let me check when I harvest tonight to see how many pages there are. I am surprised that there are so many, it should be 100 per page or 1000?

I also see you added the `parentcommunitylist` to the schema, maybe that was my fault, I think I removed it. Even so, I'm surprised there were no communities in the list. I will check again tonight after harvesting.

**Comment by alanorth** [comment]
This morning I was investigating the Altmetric harvesting to try to understand if it is correct or not. The Altmetric plugin shows 731 pages:

Screenshot 2023-10-27 at 10-28-57 AReS

I looked up one item that was previously missing an attention badge in AReS and found it is missing entirely! I looked in both the Handle and DOI filters but cannot find the item, despite it being present on DSpace 7 Test: 

- Handle: 10568/118261
- DOI: https://doi.org/10.1073/pnas.2113947119
- Link: https://dspace7test.ilri.org/items/2456ec97-c156-447b-91e9-4741c4d444a9

So something funny going on...

**Comment by mohammadsalem** [comment]
- The layout design adjustments are in place.
- For Altmetric, the harvest for the [real repositories](https://dev.openrxv.codeobia.com/explorer/admin/harvester/ares) (CGSpace, MELSpace and WorldFish DSpace) the total pages is 746 (100 per each page), however looking at the items in Elasticsearch with Altmetric data it is 19401 items
Screenshot 2023-10-29 at 4 23 27 PM

- For the items with handle 10568/118261 I could find it here https://dev.openrxv.codeobia.com/explorer/
Screenshot 2023-10-29 at 4 27 11 PM

- BTW I noticed that many items are not matched with that is in Altmetric, I was investigating and found that these are deleted handles. I tried to match Altmetric API response for the prefixes defined in the plugin with the DOI not just the handle and got an additional 100 something matches! I think these are cases where an item was submitted twice with the same DOI and the one that was tweeted got deleted.

**Comment by alanorth** [comment]
Thanks for the layout changes! Looking really good now. I love the sticky header!

As for the mysterious missing 10568/118261 handle, I swear it wasn't there when I checked. :thinking: Hmmm...

So I'm wondering about the 700+ pages of Altmetric mentions. That's 7,000 items with attention scores, but previously we were hitting limits on the free API because we were trying to crawl more than 1000 pages or so. The numbers don't make sense to me and it seems like we will be missing some scores.

Lastly, I'm thinking about a migration plan. It's good we can still harvest old DSpace instances so we can deploy the new code on a Sunday morning perhaps and you help me to make sure we get all the value mappings especially. Then we swap the indexes to the DSpace 7 sites once they are ready.

**Comment by mohammadsalem** [comment]
We were hitting the limit which was 100 pages (X 100 items per page = 10K items), now we are getting 700 something (X 100 items per page = 70K items) but only ~19.5K are matched with the handles harvested from the repositories.

Sure we can schedule a call and we do the migration together.

**Comment by alanorth** [comment]
Oh yes of course, my math was off. Good so we are confident we are capturing as many of our outputs with attention scores as possible.

Let me think about the time schedule for the migration... talk soon.

**Pull request merged**
